---
  - name: install tools
    apt: name={{item}} state=present update_cache=true
    with_items:
      - python-mysqldb

  - name: install mysql-server
    apt: name=mysql-server state=present update_cache=yes

  - name: ensure mysql listening on all ports
    lineinfile: dest=/etc/mysql/mysql.conf.d/mysqld.cnf regexp=^bind-address line="bind-address = {{ ansible_enp0s8.ipv4.address }}"
    notify: restart mysql

  - name: ensure mysql started
    service: name=mysql state=started enabled=yes
  
  - name: create demo database
    mysql_db: name={{ db_name }} state=present

  - name: create demo database user
    mysql_user: name={{ db_user_name }} password={{ db_user_pass }} priv=demo.*:ALL host={{ db_user_host }} state=present
