---
  - hosts: loadbalancer
    become: true
    gather_facts: false
    tasks:
      - name: stoping loadbalancer
        service: name=nginx state=stopped
      
      - name: wait for connections to drain
        wait_for: port=80 state=drained

  - hosts: webserver
    become: true
    gather_facts: false
    tasks:
      - name: stoping webserver
        service: name=apache2 state=stopped
      
      - name: Wait for connections to stop
        wait_for: port=80 state=stopped

  - hosts: database
    become: true
    tasks:
      - name: restarting database
        service: name=mysql state=restarted
      
      - name: ensure mysql started listening on 3306 
        wait_for: host={{ ansible_enp0s8.ipv4.address }} port=3306 state=started

  - hosts: webserver
    become: true
    gather_facts: false 
    tasks:
      - name: starting webserver
        service: name=apache2 state=started

      - name: ensure apache is listening on port 80
        wait_for: port=80



  - hosts: loadbalancer
    become: true
    gather_facts: false
    tasks:
      - name: starting loadbalancer
        service: name=nginx state=started

      - name: ensure nginx is listening on port 80
        wait_for: port=80

